"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-26 20:01:01.037845
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ENUM_TYPES = (
    "project_typ",
    "quelle",
    "scan_art",
    "pruefumfang",
    "scan_status",
    "ampel_sicherheit",
    "ampel_dsgvo",
    "freigabe",
    "ebene",
    "schwere",
    "achse",
    "nachweisgrad",
    "befund_status",
    "job_status",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("totp_secret_enc", sa.LargeBinary(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_log_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_actor_id"), "audit_log", ["actor_id"], unique=False)
    op.create_index("ix_audit_log_created_at", "audit_log", ["created_at"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "typ",
            sa.Enum("skill", "mcp-server", "plugin", "tool", "einzeldatei", name="project_typ"),
            nullable=False,
        ),
        sa.Column(
            "quelle",
            sa.Enum("datei", "auswahl", "text", "zip", "git", name="quelle"),
            nullable=False,
        ),
        sa.Column("git_url", sa.String(length=500), nullable=True),
        sa.Column(
            "delete_files_after_scan", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_einzelpruefungen", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("data_key_enc", sa.LargeBinary(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_projects_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("owner_id", "name", name=op.f("uq_projects_owner_id")),
    )
    op.create_index(op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False)
    op.create_table(
        "finding_status",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("offen", "behoben", "akzeptiert", "bestritten", name="befund_status"),
            server_default="offen",
            nullable=False,
        ),
        sa.Column("begruendung", sa.Text(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status NOT IN ('akzeptiert', 'bestritten') OR begruendung IS NOT NULL",
            name=op.f("ck_finding_status_begruendung_required"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_finding_status_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_finding_status_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_finding_status_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding_status")),
        sa.UniqueConstraint("project_id", "fingerprint", name=op.f("uq_finding_status_project_id")),
    )
    op.create_index(
        op.f("ix_finding_status_owner_id"), "finding_status", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_finding_status_project_id"), "finding_status", ["project_id"], unique=False
    )
    op.create_table(
        "packages",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("namespace", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("source_project_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_packages_owner_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_project_id"],
            ["projects.id"],
            name=op.f("fk_packages_source_project_id_projects"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_packages")),
        sa.UniqueConstraint("namespace", "name", name=op.f("uq_packages_namespace")),
    )
    op.create_index(op.f("ix_packages_owner_id"), "packages", ["owner_id"], unique=False)
    op.create_table(
        "project_versions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column("inventory_sha256", sa.String(length=64), nullable=True),
        sa.Column("file_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("bytes", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("files_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_project_versions_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_versions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_versions")),
        sa.UniqueConstraint("project_id", "number", name=op.f("uq_project_versions_project_id")),
    )
    op.create_index(
        op.f("ix_project_versions_owner_id"), "project_versions", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_project_versions_project_id"), "project_versions", ["project_id"], unique=False
    )
    op.create_table(
        "tokens",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column(
            "scopes", postgresql.ARRAY(sa.String(length=50)), server_default="{}", nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_tokens_owner_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_tokens_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tokens")),
        sa.UniqueConstraint("prefix", name=op.f("uq_tokens_prefix")),
    )
    op.create_index(op.f("ix_tokens_owner_id"), "tokens", ["owner_id"], unique=False)
    op.create_index(op.f("ix_tokens_project_id"), "tokens", ["project_id"], unique=False)
    op.create_table(
        "scans",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "scan_art", sa.Enum("schnell", "intensiv", "lokal", name="scan_art"), nullable=False
        ),
        sa.Column(
            "pruefumfang",
            sa.Enum("paket", "auswahl", "einzeldatei", name="pruefumfang"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("wartend", "laeuft", "fertig", "fehlgeschlagen", name="scan_status"),
            server_default="wartend",
            nullable=False,
        ),
        sa.Column(
            "ampel_sicherheit",
            sa.Enum("gruen", "gelb", "rot", "gesperrt", name="ampel_sicherheit"),
            nullable=True,
        ),
        sa.Column(
            "ampel_dsgvo",
            sa.Enum("gruen", "gelb", "rot", "nicht_bewertet", name="ampel_dsgvo"),
            nullable=True,
        ),
        sa.Column(
            "ampel_gesamt",
            sa.Enum("gruen", "gelb", "rot", "gesperrt", name="ampel_sicherheit"),
            nullable=True,
        ),
        sa.Column("note", sa.SmallInteger(), nullable=True),
        sa.Column(
            "freigabe",
            sa.Enum("freigegeben", "pruefung_noetig", "blockiert", name="freigabe"),
            nullable=True,
        ),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("engine_version", sa.String(length=50), nullable=True),
        sa.Column("share_token_hash", sa.Text(), nullable=True),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "scan_art <> 'schnell' OR expires_at IS NOT NULL",
            name=op.f("ck_scans_quickscan_expires"),
        ),
        sa.CheckConstraint(
            "scan_art = 'schnell' OR owner_id IS NOT NULL",
            name=op.f("ck_scans_owner_unless_quickscan"),
        ),
        sa.CheckConstraint(
            "note IS NULL OR note BETWEEN 0 AND 100", name=op.f("ck_scans_note_range")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_scans_owner_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_scans_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["project_versions.id"],
            name=op.f("fk_scans_version_id_project_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scans")),
    )
    op.create_index(op.f("ix_scans_owner_id"), "scans", ["owner_id"], unique=False)
    op.create_index(op.f("ix_scans_project_id"), "scans", ["project_id"], unique=False)
    op.create_index(op.f("ix_scans_version_id"), "scans", ["version_id"], unique=False)
    op.create_table(
        "stored_files",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_stored_files_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["project_versions.id"],
            name=op.f("fk_stored_files_version_id_project_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stored_files")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_stored_files_storage_key")),
        sa.UniqueConstraint("version_id", "path", name=op.f("uq_stored_files_version_id")),
    )
    op.create_index(op.f("ix_stored_files_owner_id"), "stored_files", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_stored_files_version_id"), "stored_files", ["version_id"], unique=False
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.String(length=200), nullable=False),
        sa.Column(
            "ebene", sa.Enum("A", "B", "C", "D", "E", "F", "G", "H", name="ebene"), nullable=False
        ),
        sa.Column("schwere", sa.Enum("K", "H", "M", "N", "I", name="schwere"), nullable=False),
        sa.Column("achse", sa.Enum("sicherheit", "dsgvo", name="achse"), nullable=False),
        sa.Column("titel", sa.String(length=200), nullable=False),
        sa.Column("erklaerung", sa.Text(), nullable=False),
        sa.Column("datei", sa.String(length=1024), nullable=True),
        sa.Column("zeile", sa.Integer(), nullable=True),
        sa.Column("beleg", sa.Text(), nullable=True),
        sa.Column(
            "nachweisgrad",
            sa.Enum(
                "statisch_erkannt",
                "per_llm_bewertet",
                "in_sandbox_beobachtet",
                "im_test_beobachtet",
                "selbstauskunft",
                name="nachweisgrad",
            ),
            nullable=False,
        ),
        sa.Column(
            "normbezug",
            postgresql.ARRAY(sa.String(length=100)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("fix", sa.Text(), nullable=False),
        sa.Column("fix_prompt", sa.Text(), nullable=False),
        sa.Column("analyzer", sa.String(length=100), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=True),
        sa.Column(
            "hochgestuft_von", sa.Enum("K", "H", "M", "N", "I", name="schwere"), nullable=True
        ),
        sa.CheckConstraint("zeile IS NULL OR zeile >= 1", name=op.f("ck_findings_zeile_positive")),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_findings_owner_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_findings_scan_id_scans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
    )
    op.create_index(op.f("ix_findings_fingerprint"), "findings", ["fingerprint"], unique=False)
    op.create_index(op.f("ix_findings_owner_id"), "findings", ["owner_id"], unique=False)
    op.create_index(op.f("ix_findings_scan_id"), "findings", ["scan_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "done", "failed", name="job_status"),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), server_default=sa.text("300"), nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_jobs_owner_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_jobs_scan_id_scans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(op.f("ix_jobs_owner_id"), "jobs", ["owner_id"], unique=False)
    op.create_index(
        "ix_jobs_queue",
        "jobs",
        ["run_after"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(op.f("ix_jobs_scan_id"), "jobs", ["scan_id"], unique=False)
    op.create_table(
        "versions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("archive_sha256", sa.String(length=64), nullable=False),
        sa.Column("signature", sa.LargeBinary(), nullable=True),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("yanked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_versions_owner_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
            name=op.f("fk_versions_package_id_packages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_versions_scan_id_scans"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_versions")),
        sa.UniqueConstraint("package_id", "version", name=op.f("uq_versions_package_id")),
    )
    op.create_index(op.f("ix_versions_owner_id"), "versions", ["owner_id"], unique=False)
    op.create_index(op.f("ix_versions_package_id"), "versions", ["package_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_versions_package_id"), table_name="versions")
    op.drop_index(op.f("ix_versions_owner_id"), table_name="versions")
    op.drop_table("versions")
    op.drop_index(op.f("ix_jobs_scan_id"), table_name="jobs")
    op.drop_index("ix_jobs_queue", table_name="jobs", postgresql_where=sa.text("status = 'queued'"))
    op.drop_index(op.f("ix_jobs_owner_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_findings_scan_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_owner_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_fingerprint"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_stored_files_version_id"), table_name="stored_files")
    op.drop_index(op.f("ix_stored_files_owner_id"), table_name="stored_files")
    op.drop_table("stored_files")
    op.drop_index(op.f("ix_scans_version_id"), table_name="scans")
    op.drop_index(op.f("ix_scans_project_id"), table_name="scans")
    op.drop_index(op.f("ix_scans_owner_id"), table_name="scans")
    op.drop_table("scans")
    op.drop_index(op.f("ix_tokens_project_id"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_owner_id"), table_name="tokens")
    op.drop_table("tokens")
    op.drop_index(op.f("ix_project_versions_project_id"), table_name="project_versions")
    op.drop_index(op.f("ix_project_versions_owner_id"), table_name="project_versions")
    op.drop_table("project_versions")
    op.drop_index(op.f("ix_packages_owner_id"), table_name="packages")
    op.drop_table("packages")
    op.drop_index(op.f("ix_finding_status_project_id"), table_name="finding_status")
    op.drop_index(op.f("ix_finding_status_owner_id"), table_name="finding_status")
    op.drop_table("finding_status")
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index("ix_audit_log_created_at", table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
    for enum_name in ENUM_TYPES:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
